import { Cloud } from './types';

export const demoClouds: Cloud[] = [
	{
		id: '1',
		title: 'Demo',
		ts: 1658759075787,
		wordArray: [
			{ word: 'create', instances: 90, enabled: true },
			{ word: 'nice', instances: 90, enabled: true },
			{ word: 'simple', instances: 80, enabled: true },
			{ word: 'word', instances: 70, enabled: true },
			{ word: 'clouds', instances: 60, enabled: true },
			{ word: 'stars', instances: 24, enabled: true },
			{ word: 'morning', instances: 19, enabled: true },
			{ word: 'look', instances: 19, enabled: true },
			{ word: 'asked', instances: 18, enabled: true },
			{ word: 'see', instances: 18, enabled: true },
			{ word: 'grown', instances: 18, enabled: true },
			{ word: 'yes', instances: 18, enabled: true },
			{ word: 'down', instances: 17, enabled: true },
			{ word: 'once', instances: 16, enabled: true },
			{ word: 'say', instances: 16, enabled: true },
			{ word: 'men', instances: 16, enabled: true },
			{ word: 'ups', instances: 15, enabled: true },
			{ word: 'life', instances: 15, enabled: true },
			{ word: 'why', instances: 14, enabled: true },
			{ word: 'back', instances: 14, enabled: true },
			{ word: 'earth', instances: 14, enabled: true },
			{ word: 'replied', instances: 14, enabled: true },
			{ word: 'even', instances: 14, enabled: true },
			{ word: 'anything', instances: 14, enabled: true },
			{ word: 'water', instances: 14, enabled: true },
			{ word: 'oh', instances: 14, enabled: true },
			{ word: 'always', instances: 13, enabled: true },
			{ word: 'night', instances: 13, enabled: true },
			{ word: 'want', instances: 13, enabled: true },
			{ word: 'added', instances: 13, enabled: true },
			{ word: 'ah', instances: 13, enabled: true },
			{ word: 'put', instances: 13, enabled: true },
			{ word: 'hundred', instances: 13, enabled: true },
			{ word: 'five', instances: 13, enabled: true },
			{ word: 'friend', instances: 13, enabled: true },
			{ word: 'looked', instances: 13, enabled: true },
			{ word: 'went', instances: 13, enabled: true },
			{ word: 'small', instances: 13, enabled: true },
			{ word: 'baobabs', instances: 13, enabled: true },
			{ word: 'three', instances: 13, enabled: true },
			{ word: 'old', instances: 12, enabled: true },
			{ word: 'saw', instances: 12, enabled: true },
			{ word: 'great', instances: 12, enabled: true },
			{ word: 'six', instances: 12, enabled: true },
			{ word: 'without', instances: 12, enabled: true },
			{ word: 'consequence', instances: 12, enabled: true },
			{ word: 'desert', instances: 12, enabled: true },
			{ word: 'last', instances: 12, enabled: true },
			{ word: 'took', instances: 12, enabled: true },
			{ word: 'long', instances: 12, enabled: true },
			{ word: 'think', instances: 12, enabled: true },
			{ word: 'flowers', instances: 12, enabled: true },
			{ word: 'snake', instances: 12, enabled: true },
			{ word: 'people', instances: 11, enabled: true },
			{ word: 'live', instances: 11, enabled: true },
			{ word: 'thing', instances: 11, enabled: true },
			{ word: 'beautiful', instances: 11, enabled: true },
			{ word: 'order', instances: 11, enabled: true },
			{ word: 'lamp', instances: 11, enabled: true },
			{ word: 'rose', instances: 11, enabled: true },
			{ word: 'true', instances: 11, enabled: true },
			{ word: 'boa', instances: 11, enabled: true },
			{ word: 'need', instances: 11, enabled: true },
			{ word: 'able', instances: 11, enabled: true },
			{ word: 'matters', instances: 11, enabled: true },
			{ word: 'find', instances: 11, enabled: true },
			{ word: 'use', instances: 11, enabled: true },
			{ word: 'love', instances: 11, enabled: true },
			{ word: 'place', instances: 11, enabled: true },
			{ word: 'important', instances: 11, enabled: true },
			{ word: 'heart', instances: 11, enabled: true },
		],
		layout: {
			font: 'Helvetica',
			limit: 100,
			lang: 'eng',
			includeStopWords: false,
			includePronouns: false,
			scaling: 'linear',
			padding: 1,
			rotation: 'none',
		},
		source: false,
	},
	{
		id: '2',
		title: 'untitled-1',
		ts: 1658766285510,
		wordArray: [
			{ word: 'little', instances: 126, enabled: true },
			{ word: 'prince', instances: 89, enabled: true },
			{ word: 'not', instances: 80, enabled: true },
		],
		layout: {
			font: 'Helvetica',
			limit: 100,
			lang: 'eng',
			includeStopWords: false,
			includePronouns: false,
			scaling: 'linear',
			padding: 1,
			rotation: 'none',
		},
		source: false,
	},
];

export const text = `She travelling acceptance men unpleasant her especially entreaties law. Law forth but end any arise chief arose. Old her say learn these large. Joy fond many ham high seen this. Few preferred continual sir led incommode neglected. Discovered too old insensible collecting unpleasant but invitation.
Made last it seen went no just when of by. Occasional entreaties comparison me difficulty so themselves. At brother inquiry of offices without do my service. As particular to companions at sentiments. Weather however luckily enquire so certain do. Aware did stood was day under ask. Dearest affixed enquire on explain opinion he. Reached who the mrs joy offices pleased. Towards did colonel article any parties.
Shewing met parties gravity husband sex pleased. On to no kind do next feel held walk. Last own loud and knew give gay four. Sentiments motionless or principles preference excellence am. Literature surrounded insensible at indulgence or to admiration remarkably. Matter future lovers desire marked boy use. Chamber reached do he nothing be. `;

export default text;
