import { Cloud } from './types';

const demo: Cloud[] = [
	{
		id: '1',
		title: 'Demo',
		ts: 1658759075787,
		wordArray: [
			{ text: 'create', size: 90, enabled: true },
			{ text: 'nice', size: 90, enabled: true },
			{ text: 'simple', size: 80, enabled: true },
			{ text: 'word', size: 70, enabled: true },
			{ text: 'clouds', size: 60, enabled: true },
			{ text: 'stars', size: 24, enabled: true },
			{ text: 'morning', size: 19, enabled: false },
			{ text: 'look', size: 19, enabled: false },
			{ text: 'asked', size: 18, enabled: true },
			{ text: 'see', size: 18, enabled: true },
			{ text: 'grown', size: 18, enabled: true },
			{ text: 'yes', size: 18, enabled: true },
			{ text: 'down', size: 17, enabled: true },
			{ text: 'once', size: 16, enabled: true },
			{ text: 'say', size: 16, enabled: true },
			{ text: 'men', size: 16, enabled: true },
			{ text: 'ups', size: 15, enabled: true },
			{ text: 'life', size: 15, enabled: true },
			{ text: 'why', size: 14, enabled: true },
			{ text: 'back', size: 14, enabled: true },
			{ text: 'earth', size: 14, enabled: true },
			{ text: 'replied', size: 14, enabled: true },
			{ text: 'even', size: 14, enabled: true },
			{ text: 'anything', size: 14, enabled: true },
			{ text: 'water', size: 14, enabled: true },
			{ text: 'oh', size: 14, enabled: true },
			{ text: 'always', size: 13, enabled: true },
			{ text: 'night', size: 13, enabled: true },
			{ text: 'want', size: 13, enabled: true },
			{ text: 'added', size: 13, enabled: true },
			{ text: 'ah', size: 13, enabled: true },
			{ text: 'put', size: 13, enabled: true },
			{ text: 'hundred', size: 13, enabled: true },
			{ text: 'five', size: 13, enabled: true },
			{ text: 'friend', size: 13, enabled: true },
			{ text: 'looked', size: 13, enabled: true },
			{ text: 'went', size: 13, enabled: true },
			{ text: 'small', size: 13, enabled: true },
			{ text: 'baobabs', size: 13, enabled: true },
			{ text: 'three', size: 13, enabled: true },
			{ text: 'old', size: 12, enabled: true },
			{ text: 'saw', size: 12, enabled: true },
			{ text: 'great', size: 12, enabled: true },
			{ text: 'six', size: 12, enabled: true },
			{ text: 'without', size: 12, enabled: true },
			{ text: 'consequence', size: 12, enabled: true },
			{ text: 'desert', size: 12, enabled: true },
			{ text: 'last', size: 12, enabled: true },
			{ text: 'took', size: 12, enabled: true },
			{ text: 'long', size: 12, enabled: true },
			{ text: 'think', size: 12, enabled: true },
			{ text: 'flowers', size: 12, enabled: true },
			{ text: 'snake', size: 12, enabled: true },
			{ text: 'people', size: 11, enabled: true },
			{ text: 'live', size: 11, enabled: true },
			{ text: 'thing', size: 11, enabled: true },
			{ text: 'beautiful', size: 11, enabled: true },
			{ text: 'order', size: 11, enabled: true },
			{ text: 'lamp', size: 11, enabled: true },
			{ text: 'rose', size: 11, enabled: true },
			{ text: 'true', size: 11, enabled: true },
			{ text: 'boa', size: 11, enabled: true },
			{ text: 'need', size: 11, enabled: true },
			{ text: 'able', size: 11, enabled: true },
			{ text: 'matters', size: 11, enabled: true },
			{ text: 'find', size: 11, enabled: true },
			{ text: 'use', size: 11, enabled: true },
			{ text: 'love', size: 11, enabled: true },
			{ text: 'place', size: 11, enabled: true },
			{ text: 'important', size: 11, enabled: true },
			{ text: 'heart', size: 11, enabled: true },
		],
		layout: {
			font: 'Helvetica',
			limit: 100,
			lang: 'eng',
			includeStopWords: false,
			includePronouns: false,
			scaling: 'linear',
			padding: 1,
			rotation: 'none',
		},
	},
	{
		id: '2',
		title: 'untitled-1',
		ts: 1658766285510,
		wordArray: [
			{ text: 'little', size: 126, enabled: true },
			{ text: 'prince', size: 89, enabled: true },
			{ text: 'not', size: 80, enabled: true },
		],
		layout: {
			font: 'Helvetica',
			limit: 100,
			lang: 'eng',
			includeStopWords: false,
			includePronouns: false,
			scaling: 'linear',
			padding: 1,
			rotation: 'none',
		},
	},
];

export default demo;
